### ISSUE TITLE
Please add gearbox feature

### ISSUE THREAD

**Issue by Willem1981** [Rembootje/basic-speedometer#1]
Please add a gearbox, so we know what gear the vehicle is in

**Comment by Rembootje** [comment]
Thank you for your input! I will be making it ASAP! For now, I hope you enjoy the current version!

**Comment by Rembootje** [comment]
The gearbox indicator has been added in the new version (v1.1.0).
Thank you for this feedback, if you have any more issues or idea's, feel free to let me know!
